### ISSUE TITLE
missing tpDcc.libs.python.plugin

### ISSUE THREAD

**Issue by qeeji** [tpDcc/tpDcc-libs-python#2]
Hi Tomas ,

Thanks for sharing your works , it's a great idea.

Just report to you about the missiong script issue which happened on my maya script editor , check it out : 
# Error: ImportError: file G:/xM/Dropbox/hzWork/hzNet/hzTools/libs/tpDcc/tpDcc\core\command.py line 20: cannot import name plugin # 

Thank you so much ,

**Comment by tpoveda** [comment]
Bug should be fixed if you pull latest changes from master branch.
